name: Android CI

on:
  push:
    branches: [ "kt-n" ]
  pull_request:
    branches: [ "kt-n" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Prepare environment
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradle
    
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        

    - name: CHMOD GRADLEW
      run: chmod 777 ./gradlew
    - name: Build with Gradle
      run: gradle build
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
